# Generated by Django 3.0.5 on 2020-09-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Corporate Headoffice', 'Corporate Headoffice'), ('Operations Departments', 'Operations Departments'), ('Work Station', 'Work Station'), ('Marketing Division', 'Marketing Division')], default='1', max_length=100)),
                ('desc', models.CharField(max_length=1000, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('inc_location', models.CharField(max_length=200, null=True)),
                ('severety', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Savere', 'Savere'), ('Fatal', 'Fatal')], default='1', max_length=100)),
                ('cause', models.CharField(max_length=300, null=True)),
                ('action', models.CharField(max_length=300, null=True)),
                ('environment', models.BooleanField()),
                ('injury', models.BooleanField()),
                ('damage', models.BooleanField()),
                ('vehicle', models.BooleanField()),
            ],
        ),
    ]
