# Generated by Django 3.0.5 on 2020-09-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200920_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='damage',
            field=models.BooleanField(default=False, verbose_name='damage'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='environment',
            field=models.BooleanField(default=False, verbose_name='environment'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='injury',
            field=models.BooleanField(default=False, verbose_name='injury'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='vehicle',
            field=models.BooleanField(default=False, verbose_name='vehicle'),
        ),
    ]
